/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.supermercadoproyecto.login;

import com.mycompany.supermercadoproyecto.login.Home;
import com.mycompany.supermercadoproyecto.administrador.HerramientasAdministrador;
import com.supermercado.dao.EmpleadoDAO;
import com.supermercado.modelos.Empleado;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import javax.swing.BorderFactory;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author MEDAC
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        jTextField1.setForeground(Color.GRAY);
    jTextField1.setText("DNI/NIF");

    jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
        @Override
        public void focusGained(java.awt.event.FocusEvent evt) {
            if (jTextField1.getText().equals("DNI/NIF")) {
                jTextField1.setText("");
                jTextField1.setForeground(Color.BLACK);
            }
        }

        @Override
        public void focusLost(java.awt.event.FocusEvent evt) {
            if (jTextField1.getText().isEmpty()) {
                jTextField1.setForeground(Color.GRAY);
                jTextField1.setText("DNI/NIF");
            }
        }
    });

    // --- PLACEHOLDER CONTRASEÑA ---
    jTextField2.setForeground(Color.GRAY);
    jTextField2.setText("Contraseña");

    jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
        @Override
        public void focusGained(java.awt.event.FocusEvent evt) {
            if (jTextField2.getText().equals("Contraseña")) {
                jTextField2.setText("");
                jTextField2.setForeground(Color.BLACK);
            }
        }

        @Override
        public void focusLost(java.awt.event.FocusEvent evt) {
            if (jTextField2.getText().isEmpty()) {
                jTextField2.setForeground(Color.GRAY);
                jTextField2.setText("Contraseña");
            }
        }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlPrincipal = new javax.swing.JPanel();
        pnlHome = new com.mycompany.supermercadoproyecto.recursos.BackgroundPanel("/fondo.png");
        pnlHome = new com.mycompany.supermercadoproyecto.recursos.BackgroundPanel("/fondo.png")
        ;
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPrincipal.setPreferredSize(new java.awt.Dimension(800, 800));
        pnlPrincipal.setLayout(new java.awt.BorderLayout());

        pnlHome.setLayout(new java.awt.GridBagLayout());

        jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        jTextField1.setText("DNI/NIF...");
        jTextField1.setPreferredSize(new java.awt.Dimension(150, 33));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        pnlHome.add(jTextField1, new java.awt.GridBagConstraints());

        jTextField2.setForeground(new java.awt.Color(153, 153, 153));
        jTextField2.setText("Contraseña...");
        jTextField2.setMinimumSize(new java.awt.Dimension(64, 25));
        jTextField2.setPreferredSize(new java.awt.Dimension(150, 33));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(7, 4, 7, 1);
        pnlHome.add(jTextField2, gridBagConstraints);

        jButton1.setText("INICIAR SESION");
        jButton1.setPreferredSize(new java.awt.Dimension(150, 22));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(17, 17, 3, 17);
        pnlHome.add(jButton1, gridBagConstraints);

        jButton2.setText("¿No tienes usuario?");
        jButton2.setPreferredSize(new java.awt.Dimension(150, 22));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        pnlHome.add(jButton2, gridBagConstraints);

        pnlPrincipal.add(pnlHome, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
    // 1. Obtener y limpiar datos
    String dni = jTextField1.getText().trim();
    String pass = new String(jTextField2.getText()); 

    // 2. Validación de campos vacíos o placeholders
    if (dni.isEmpty() || pass.isEmpty() || dni.equals("DNI/NIF...") || pass.equals("Contraseña...")) {
        JOptionPane.showMessageDialog(this, "Por favor, rellene todos los campos.", "Campos incompletos", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 3. INTENTO 1: Buscar en la tabla de Empleados
    com.supermercado.dao.EmpleadoDAO empDao = new com.supermercado.dao.EmpleadoDAO();
    com.supermercado.modelos.Empleado empleado = empDao.validarLogin(dni, pass);

    if (empleado != null) {
        ejecutarLoginEmpleado(empleado);
    } else {
        // 4. INTENTO 2: Si no es empleado, buscar en la tabla de Clientes
        com.supermercado.dao.ClienteDAO cliDao = new com.supermercado.dao.ClienteDAO();
        com.supermercado.modelos.Cliente cliente = cliDao.validarLogin(dni, pass);

        if (cliente != null) {
            ejecutarLoginCliente(cliente);
        } else {
            // 5. Fallo total
            JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos", "Error de acceso", JOptionPane.ERROR_MESSAGE);
        }
    }
}

// --- MÉTODOS AUXILIARES PARA MANTENER EL CÓDIGO LIMPIO ---

private void ejecutarLoginEmpleado(com.supermercado.modelos.Empleado empleado) {
    com.supermercado.util.Sesion.setEmpleado(empleado);
    
    // Registro de Log
    try {
        new com.supermercado.dao.LogDAO().registrarLog(empleado, "Inicio de sesión");
    } catch (Exception ex) {
        System.err.println("Error en Log: " + ex.getMessage());
    }

    JOptionPane.showMessageDialog(this, "Bienvenido, " + empleado.getNombre());

    try {
        String rol = empleado.getRol().name().toLowerCase();
        if (rol.equals("admin") || rol.equals("gerente")) {
            com.mycompany.supermercadoproyecto.administrador.HerramientasAdministrador vAdmin = new com.mycompany.supermercadoproyecto.administrador.HerramientasAdministrador();
            vAdmin.setVisible(true);
            vAdmin.setLocationRelativeTo(null);
        } else {
            com.mycompany.supermercadoproyecto.login.Home vHome = new com.mycompany.supermercadoproyecto.login.Home();
            vHome.setVisible(true);
            vHome.setLocationRelativeTo(null);
        }
        this.dispose();
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error al abrir ventana: " + ex.getMessage());
    }
}

private void ejecutarLoginCliente(com.supermercado.modelos.Cliente cliente) {
    JOptionPane.showMessageDialog(this, "Bienvenido Cliente: " + cliente.getNombre());
    
    try {
        // Asegúrate de que esta ruta coincida con la ubicación real de tu clase
        com.mycompany.supermercadoproyecto.Acceso_clientes vCliente = new com.mycompany.supermercadoproyecto.Acceso_clientes();
        vCliente.setVisible(true);
        vCliente.setLocationRelativeTo(null);
        this.dispose();
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error al abrir ventana de clientes: " + ex.getMessage());
    }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        abrirFormularioRegistroCliente();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables

    private void abrirFormularioRegistroCliente() {
        // 1. --- ESTILO VISUAL ---
    Color fondo = new Color(255, 255, 255);
    Font fuenteLabel = new Font("Segoe UI", Font.PLAIN, 13);
    
    // 2. --- CAMPOS DEL CLIENTE ---
    JTextField txtNombre = new JTextField();
    JTextField txtApellido = new JTextField();
    JTextField txtDni = new JTextField();
    JTextField txtTelefono = new JTextField();
    JTextField txtEmail = new JTextField();
    JPasswordField txtPass = new JPasswordField();

    // Configuración de tamaño
    Dimension dim = new Dimension(220, 30);
    JComponent[] campos = {txtNombre, txtApellido, txtDni, txtTelefono, txtEmail, txtPass};
    for (JComponent c : campos) { c.setPreferredSize(dim); }

    // 3. --- DISEÑO DEL PANEL ---
    JPanel panel = new JPanel(new GridBagLayout());
    panel.setBackground(fondo);
    panel.setBorder(BorderFactory.createEmptyBorder(15, 15, 15, 15));
    GridBagConstraints gbc = new GridBagConstraints();
    gbc.insets = new Insets(5, 10, 5, 10);
    gbc.fill = GridBagConstraints.HORIZONTAL;

    // Título dentro del panel
    JLabel titulo = new JLabel("CREAR CUENTA NUEVA");
    titulo.setFont(new Font("Segoe UI", Font.BOLD, 16));
    titulo.setForeground(new Color(0, 102, 204));
    gbc.gridx = 0; gbc.gridy = 0; gbc.gridwidth = 2;
    gbc.insets = new Insets(0, 10, 15, 10);
    panel.add(titulo, gbc);

    // Reset gridwidth para los campos
    gbc.gridwidth = 1;
    gbc.insets = new Insets(5, 10, 5, 10);

    // Añadir filas (usando el método agregarCampo que ya tienes o manualmente)
    int fila = 1;
    String[] etiquetas = {"Nombre:", "Apellido:", "DNI:", "Teléfono:", "Email:", "Contraseña:"};
    for (int i = 0; i < etiquetas.length; i++) {
        gbc.gridy = fila; gbc.gridx = 0;
        panel.add(new JLabel(etiquetas[i]), gbc);
        gbc.gridx = 1;
        panel.add(campos[i], gbc);
        fila++;
    }

    // 4. --- MOSTRAR DIÁLOGO ---
    int result = JOptionPane.showConfirmDialog(this, panel, "Registro de Cliente", 
            JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

    // 5. --- GUARDAR EN LA TABLA CLIENTES ---
    if (result == JOptionPane.OK_OPTION) {
        // Validar que no estén vacíos
        if (txtNombre.getText().isEmpty() || txtDni.getText().isEmpty() || new String(txtPass.getPassword()).isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nombre, DNI y Contraseña son obligatorios.");
            return;
        }

        try {
            com.supermercado.modelos.Cliente nuevoCli = new com.supermercado.modelos.Cliente();
            nuevoCli.setNombre(txtNombre.getText().trim());
            nuevoCli.setApellido(txtApellido.getText().trim());
            nuevoCli.setDni(txtDni.getText().trim());
            nuevoCli.setTelefono(txtTelefono.getText().trim());
            nuevoCli.setEmail(txtEmail.getText().trim());
            
            // Usamos el DNI como usuario por defecto para el cliente
            nuevoCli.setUsuario(txtDni.getText().trim());
            nuevoCli.setPassword(new String(txtPass.getPassword()));
            nuevoCli.setActivo(true);

            // Llamamos al DAO de clientes que creamos antes
            com.supermercado.dao.ClienteDAO dao = new com.supermercado.dao.ClienteDAO();
            dao.registrar(nuevoCli);
            com.supermercado.dao.LogDAO logDao = new com.supermercado.dao.LogDAO();
            logDao.registrarLog(null, "Nuevo auto-registro de cliente: " + nuevoCli.getDni());
            JOptionPane.showMessageDialog(this, "¡Cuenta creada con éxito! Ya puedes iniciar sesión con tu DNI.");
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al registrar cliente: " + ex.getMessage());
        }
    }
    }
}
