/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.supermercadoproyecto;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.Insets;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author MEDAC
 */
public class Gestión_empleados extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Gestión_empleados.class.getName());

    /**
     * Creates new form Home
     */
    public Gestión_empleados() {
        initComponents();
       // Aseguramos layout de pnlHome
GridBagLayout layout = (GridBagLayout) pnlHome.getLayout();
pnlHome.remove(btnAlta);
pnlHome.remove(btnModificar);
pnlHome.remove(btnBaja);

// Creamos un subpanel para agrupar los botones
JPanel pnlBotones = new JPanel(new FlowLayout(FlowLayout.CENTER, 75, 0));
pnlBotones.setOpaque(false); // Fondo transparente
pnlBotones.add(btnAlta);
pnlBotones.add(btnModificar);
pnlBotones.add(btnBaja);

// Configuramos constraints para centrar el bloque
GridBagConstraints gbc = new GridBagConstraints();
gbc.gridx = 0;
gbc.gridy = 1;
gbc.gridwidth = 3;
gbc.anchor = GridBagConstraints.CENTER;
gbc.fill = GridBagConstraints.NONE;
gbc.weightx = 1.0;
gbc.weighty = 1.0;

// Añadimos el subpanel al pnlHome
pnlHome.add(pnlBotones, gbc);

// Forzamos actualización visual
pnlHome.revalidate();
pnlHome.repaint();
// Centrar el jLabel1 arriba
GridBagConstraints gbcTitulo = new GridBagConstraints();
gbcTitulo.gridx = 0;
gbcTitulo.gridy = 0;
gbcTitulo.gridwidth = 3; // mismo número de columnas que uses para los botones
gbcTitulo.anchor = GridBagConstraints.PAGE_START;
gbcTitulo.fill = GridBagConstraints.NONE;
gbcTitulo.weightx = 1.0;
gbcTitulo.weighty = 0.0;
gbcTitulo.insets = new Insets(30, 0, 20, 0);

pnlHome.add(jblEmpleados, gbcTitulo);
pnlHome.revalidate();
pnlHome.repaint();

  

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlPrincipal = new javax.swing.JPanel();
        pnlBorde = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnRecargar = new javax.swing.JButton();
        btnOpciones = new javax.swing.JButton();
        pnlHome = new com.mycompany.supermercadoproyecto.BackgroundPanel("/fondo.png");
        pnlHome = new com.mycompany.supermercadoproyecto.BackgroundPanel("/fondo.png")
        ;
        jblEmpleados = new javax.swing.JLabel();
        btnAlta = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnBaja = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPrincipal.setLayout(new java.awt.BorderLayout());

        pnlBorde.setBackground(new java.awt.Color(204, 204, 204));
        pnlBorde.setPreferredSize(new java.awt.Dimension(800, 25));
        pnlBorde.setLayout(new javax.swing.BoxLayout(pnlBorde, javax.swing.BoxLayout.LINE_AXIS));

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home.png"))); // NOI18N
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        pnlBorde.add(btnHome);

        btnRecargar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recargar.png"))); // NOI18N
        btnRecargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecargarActionPerformed(evt);
            }
        });
        pnlBorde.add(btnRecargar);

        btnOpciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/opciones.png"))); // NOI18N
        pnlBorde.add(btnOpciones);

        pnlPrincipal.add(pnlBorde, java.awt.BorderLayout.PAGE_START);

        pnlHome.setLayout(new java.awt.GridBagLayout());

        jblEmpleados.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 48)); // NOI18N
        jblEmpleados.setForeground(new java.awt.Color(255, 255, 255));
        jblEmpleados.setText("Gestión de empleados");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        pnlHome.add(jblEmpleados, gridBagConstraints);

        btnAlta.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btnAlta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alta.png"))); // NOI18N
        btnAlta.setText("Alta");
        btnAlta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 19;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 28, 10, 28);
        pnlHome.add(btnAlta, gridBagConstraints);

        btnModificar.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modificación.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 19;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 28, 10, 28);
        pnlHome.add(btnModificar, gridBagConstraints);

        btnBaja.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btnBaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baja.png"))); // NOI18N
        btnBaja.setText("Baja");
        btnBaja.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 19;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 28, 10, 28);
        pnlHome.add(btnBaja, gridBagConstraints);

        pnlPrincipal.add(pnlHome, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
    Home home = new Home();
    home.setVisible(true);
    home.setLocationRelativeTo(null); // Centra la ventana

    // Cierra la ventana actual
    this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaActionPerformed
                                       
    // Crear iconos
    ImageIcon iconDni = new ImageIcon(getClass().getResource("/dni.png"));
    ImageIcon iconPass = new ImageIcon(getClass().getResource("/contraseña.png"));
    ImageIcon iconCheck = new ImageIcon(getClass().getResource("/check.png"));

    // Crear campos de texto
    JTextField txtDni = new JTextField();
    JPasswordField txtPass1 = new JPasswordField();
    JPasswordField txtPass2 = new JPasswordField();

    // Ajustar tamaño de los campos (más largos)
    Dimension fieldSize = new Dimension(240, 28);
    txtDni.setPreferredSize(fieldSize);
    txtPass1.setPreferredSize(fieldSize);
    txtPass2.setPreferredSize(fieldSize);

    // Panel principal con GridBagLayout
    JPanel panel = new JPanel(new GridBagLayout());
    panel.setBackground(new Color(245, 245, 245)); // gris suave
    panel.setPreferredSize(new Dimension(450, 200)); // ancho y alto más amplios

    GridBagConstraints gbc = new GridBagConstraints();
    gbc.insets = new Insets(10, 10, 10, 10);
    gbc.anchor = GridBagConstraints.WEST;

    // ===== Fila 1: DNI =====
    gbc.gridx = 0; gbc.gridy = 0;
    panel.add(new JLabel(iconDni), gbc);
    gbc.gridx = 1;
    panel.add(new JLabel("DNI:"), gbc);
    gbc.gridx = 2;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    gbc.weightx = 1.0;
    panel.add(txtDni, gbc);

    // ===== Fila 2: Contraseña =====
    gbc.gridx = 0; gbc.gridy = 1;
    gbc.fill = GridBagConstraints.NONE;
    gbc.weightx = 0;
    panel.add(new JLabel(iconPass), gbc);
    gbc.gridx = 1;
    panel.add(new JLabel("Establecer contraseña:"), gbc);
    gbc.gridx = 2;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    gbc.weightx = 1.0;
    panel.add(txtPass1, gbc);

    // ===== Fila 3: Confirmar contraseña =====
    gbc.gridx = 0; gbc.gridy = 2;
    gbc.fill = GridBagConstraints.NONE;
    gbc.weightx = 0;
    panel.add(new JLabel(iconPass), gbc);
    gbc.gridx = 1;
    panel.add(new JLabel("Confirmar contraseña:"), gbc);
    gbc.gridx = 2;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    gbc.weightx = 1.0;
    panel.add(txtPass2, gbc);

    // Mostrar JOptionPane más amplio
    int option = JOptionPane.showConfirmDialog(
        this,
        panel,
        "Alta de empleado",
        JOptionPane.OK_CANCEL_OPTION,
        JOptionPane.PLAIN_MESSAGE
    );

    // Validar datos si pulsa "Aceptar"
    
            if (option == JOptionPane.OK_OPTION) {
        String dni = txtDni.getText().trim();
        String pass1 = new String(txtPass1.getPassword());
        String pass2 = new String(txtPass2.getPassword());

        if (dni.isEmpty() || pass1.isEmpty() || pass2.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Todos los campos son obligatorios.",
                "Error",
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!pass1.equals(pass2)) {
            JOptionPane.showMessageDialog(this,
                "Las contraseñas no coinciden.",
                "Error",
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        JOptionPane.showMessageDialog(this,
            "Empleado dado de alta correctamente.",
            "Éxito",
            JOptionPane.INFORMATION_MESSAGE,
            iconCheck);
        
    }
       
    



        // TODO add your handling code here:
    }//GEN-LAST:event_btnAltaActionPerformed

    private void btnRecargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecargarActionPerformed
    this.dispose(); // Cierra la ventana actual
    Gestión_empleados nuevaVentana = new Gestión_empleados(); // Crea una nueva instancia
    nuevaVentana.setVisible(true); // Muestra la nueva
    nuevaVentana.setLocationRelativeTo(null); // La centra en pantalla
    }//GEN-LAST:event_btnRecargarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
     // Iconos
    ImageIcon iconDni = new ImageIcon(getClass().getResource("/dni.png"));
    ImageIcon iconPass = new ImageIcon(getClass().getResource("/contraseña.png"));
    ImageIcon iconCheck = new ImageIcon(getClass().getResource("/check.png"));

    // Campos
    JTextField txtDni = new JTextField();
    JTextField txtNuevoNombre = new JTextField();
    JPasswordField txtNuevaPass = new JPasswordField();

    // Tamaño de campos
    Dimension fieldSize = new Dimension(240, 28);
    txtDni.setPreferredSize(fieldSize);
    txtNuevoNombre.setPreferredSize(fieldSize);
    txtNuevaPass.setPreferredSize(fieldSize);

    // Panel con GridBagLayout
    JPanel panel = new JPanel(new GridBagLayout());
    panel.setBackground(new Color(245, 245, 245));
    panel.setPreferredSize(new Dimension(450, 200));
    GridBagConstraints gbc = new GridBagConstraints();
    gbc.insets = new Insets(10, 10, 10, 10);
    gbc.anchor = GridBagConstraints.WEST;

    // ===== Fila 1: DNI =====
    gbc.gridx = 0; gbc.gridy = 0;
    panel.add(new JLabel(iconDni), gbc);
    gbc.gridx = 1;
    panel.add(new JLabel("DNI del empleado:"), gbc);
    gbc.gridx = 2;
    panel.add(txtDni, gbc);

    // ===== Fila 2: Nuevo nombre =====
    gbc.gridx = 0; gbc.gridy = 1;
    panel.add(new JLabel(iconDni), gbc);
    gbc.gridx = 1;
    panel.add(new JLabel("Nuevo nombre:"), gbc);
    gbc.gridx = 2;
    panel.add(txtNuevoNombre, gbc);

    // ===== Fila 3: Nueva contraseña =====
    gbc.gridx = 0; gbc.gridy = 2;
    panel.add(new JLabel(iconPass), gbc);
    gbc.gridx = 1;
    panel.add(new JLabel("Nueva contraseña:"), gbc);
    gbc.gridx = 2;
    panel.add(txtNuevaPass, gbc);

    // Mostrar JOptionPane
    int option = JOptionPane.showConfirmDialog(
        this,
        panel,
        "Modificar empleado",
        JOptionPane.OK_CANCEL_OPTION,
        JOptionPane.PLAIN_MESSAGE
    );

    if (option == JOptionPane.OK_OPTION) {
        String dni = txtDni.getText().trim();
        String nuevoNombre = txtNuevoNombre.getText().trim();
        String nuevaPass = new String(txtNuevaPass.getPassword());

        if (dni.isEmpty() || nuevoNombre.isEmpty() || nuevaPass.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Todos los campos son obligatorios.",
                "Error",
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Mostrar mensaje simulado de modificación
        JOptionPane.showMessageDialog(this,
            "Empleado con DNI " + dni + " modificado correctamente.\n"
            + "Nuevo nombre: " + nuevoNombre,
            "Modificación realizada",
            JOptionPane.INFORMATION_MESSAGE,
            iconCheck);
          }

    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaActionPerformed
   // Iconos
    ImageIcon iconDni = new ImageIcon(getClass().getResource("/dni.png"));
    ImageIcon iconCheck = new ImageIcon(getClass().getResource("/check.png"));

    // Campo para el DNI
    JTextField txtDni = new JTextField();
    txtDni.setPreferredSize(new Dimension(260, 28)); // Más ancho

    // Panel principal con GridBagLayout
    JPanel panel = new JPanel(new GridBagLayout());
    panel.setBackground(new Color(245, 245, 245));
    panel.setPreferredSize(new Dimension(500, 180)); // Más grande horizontalmente
    GridBagConstraints gbc = new GridBagConstraints();
    gbc.insets = new Insets(15, 15, 15, 15);
    gbc.anchor = GridBagConstraints.WEST;

    // ===== Fila 1: DNI =====
    gbc.gridx = 0; gbc.gridy = 0;
    panel.add(new JLabel(iconDni), gbc);
    gbc.gridx = 1;
    panel.add(new JLabel("DNI del empleado a eliminar:"), gbc);
    gbc.gridx = 2;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    gbc.weightx = 1.0;
    panel.add(txtDni, gbc);

    // Mostrar JOptionPane
    int option = JOptionPane.showConfirmDialog(
        this,
        panel,
        "Eliminar empleado",
        JOptionPane.OK_CANCEL_OPTION,
        JOptionPane.PLAIN_MESSAGE
    );

    if (option == JOptionPane.OK_OPTION) {
        String dni = txtDni.getText().trim();

        if (dni.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Debes introducir el DNI del empleado.",
                "Error",
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Confirmación antes de eliminar
        int confirm = JOptionPane.showConfirmDialog(
            this,
            "¿Seguro que quieres eliminar al empleado con DNI " + dni + "?",
            "Confirmar eliminación",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
        );

        if (confirm == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this,
                "Empleado con DNI " + dni + " eliminado correctamente.",
                "Eliminación completada",
                JOptionPane.INFORMATION_MESSAGE,
                iconCheck);
        }
    }
    }//GEN-LAST:event_btnBajaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Gestión_empleados().setVisible(true));
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlta;
    private javax.swing.JButton btnBaja;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnOpciones;
    private javax.swing.JButton btnRecargar;
    private javax.swing.JLabel jblEmpleados;
    private javax.swing.JPanel pnlBorde;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}

