/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.supermercadoproyecto;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author MEDAC
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    public Login() {
        setExtendedState(MAXIMIZED_BOTH);
        initComponents();
        jTextField1.setForeground(Color.GRAY);
    jTextField1.setText("DNI/NIF");

    jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
        @Override
        public void focusGained(java.awt.event.FocusEvent evt) {
            if (jTextField1.getText().equals("DNI/NIF")) {
                jTextField1.setText("");
                jTextField1.setForeground(Color.BLACK);
            }
        }

        @Override
        public void focusLost(java.awt.event.FocusEvent evt) {
            if (jTextField1.getText().isEmpty()) {
                jTextField1.setForeground(Color.GRAY);
                jTextField1.setText("DNI/NIF");
            }
        }
    });

    // --- PLACEHOLDER CONTRASEÑA ---
    jTextField2.setForeground(Color.GRAY);
    jTextField2.setText("Contraseña");

    jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
        @Override
        public void focusGained(java.awt.event.FocusEvent evt) {
            if (jTextField2.getText().equals("Contraseña")) {
                jTextField2.setText("");
                jTextField2.setForeground(Color.BLACK);
            }
        }

        @Override
        public void focusLost(java.awt.event.FocusEvent evt) {
            if (jTextField2.getText().isEmpty()) {
                jTextField2.setForeground(Color.GRAY);
                jTextField2.setText("Contraseña");
            }
        }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlPrincipal = new javax.swing.JPanel();
        pnlBorde = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnRecargar = new javax.swing.JButton();
        btnOpciones = new javax.swing.JButton();
        pnlHome = new com.mycompany.supermercadoproyecto.BackgroundPanel("/fondo.png");
        pnlHome = new com.mycompany.supermercadoproyecto.BackgroundPanel("/fondo.png")
        ;
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPrincipal.setLayout(new java.awt.BorderLayout());

        pnlBorde.setBackground(new java.awt.Color(204, 204, 204));
        pnlBorde.setPreferredSize(new java.awt.Dimension(800, 25));
        pnlBorde.setLayout(new javax.swing.BoxLayout(pnlBorde, javax.swing.BoxLayout.LINE_AXIS));

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home.png"))); // NOI18N
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        pnlBorde.add(btnHome);

        btnRecargar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recargar.png"))); // NOI18N
        btnRecargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecargarActionPerformed(evt);
            }
        });
        pnlBorde.add(btnRecargar);

        btnOpciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/opciones.png"))); // NOI18N
        pnlBorde.add(btnOpciones);

        pnlPrincipal.add(pnlBorde, java.awt.BorderLayout.PAGE_START);

        pnlHome.setLayout(new java.awt.GridBagLayout());

        jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        jTextField1.setText("DNI/NIF...");
        jTextField1.setPreferredSize(new java.awt.Dimension(150, 26));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        pnlHome.add(jTextField1, new java.awt.GridBagConstraints());

        jTextField2.setForeground(new java.awt.Color(153, 153, 153));
        jTextField2.setText("Contraseña...");
        jTextField2.setPreferredSize(new java.awt.Dimension(150, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(7, 4, 7, 1);
        pnlHome.add(jTextField2, gridBagConstraints);

        jButton1.setText("INICIAR SESION");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(17, 17, 17, 17);
        pnlHome.add(jButton1, gridBagConstraints);

        pnlPrincipal.add(pnlHome, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        Home home = new Home();
        home.setVisible(true);
        home.setLocationRelativeTo(null); // Centra la ventana

        // Cierra la ventana actual
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnRecargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecargarActionPerformed
        this.dispose(); // Cierra la ventana actual
        Home nuevaVentana = new Home(); // Crea una nueva instancia
        nuevaVentana.setVisible(true); // Muestra la nueva
        nuevaVentana.setLocationRelativeTo(null); // La centra en pantalla
    }//GEN-LAST:event_btnRecargarActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String dniCorrecto = "12345678A";
    String passCorrecta = "1234";

    String dniIntroducido = jTextField1.getText();
    String passIntroducida = jTextField2.getText();

    if (dniIntroducido.equals(dniCorrecto) && passIntroducida.equals(passCorrecta)) {
        JOptionPane.showMessageDialog(this, "Inicio de sesión correcto");

        // ABRIR HOME.JAVA
        Home ventanaHome = new Home();
        ventanaHome.setVisible(true);
        ventanaHome.setLocationRelativeTo(null); // Centrar pantalla
        this.dispose(); // Cierra el Login
    } 
    else {
        JOptionPane.showMessageDialog(this, "DNI o contraseña incorrectos");
    } 
    
       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnOpciones;
    private javax.swing.JButton btnRecargar;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel pnlBorde;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
