/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.supermercadoproyecto.proveedores;

import com.mycompany.supermercadoproyecto.login.Home;
import java.awt.Color;

/**
 *
 * @author MEDAC
 */
public class proveedores extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(proveedores.class.getName());

    /**
     * Creates new form proveedores
     */
    public proveedores() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }
    
        private void cambiarPanel(javax.swing.JPanel nuevoPanel) {
        // Eliminar todo lo que haya actualmente
        pnlContenido.removeAll();

        // Agregar el nuevo panel en el centro
        pnlContenido.add(nuevoPanel);

        // Recalcular el layout (tamaños, posiciones)
        pnlContenido.revalidate();

        // Redibujar visualmente en la pantalla
        pnlContenido.repaint();
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nombreAdmJlb = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        txtBusca = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Añadirbnt = new javax.swing.JButton();
        eliminartbn = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        pnlBorde = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnRecargar = new javax.swing.JButton();
        btnOpciones = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel11 = new javax.swing.JPanel();
        chuchepriasbtn = new javax.swing.JButton();
        Snacksbtn = new javax.swing.JButton();
        Frutasbtn = new javax.swing.JButton();
        bebidasbtn = new javax.swing.JButton();
        pescadosbtn = new javax.swing.JButton();
        alcoholbtn = new javax.swing.JButton();
        CarnesBtn = new javax.swing.JButton();
        pnlContenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel7.setLayout(new java.awt.BorderLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(200, 200));
        jPanel1.setPreferredSize(new java.awt.Dimension(440, 100));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel12.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setPreferredSize(new java.awt.Dimension(155, 100));
        jPanel2.setLayout(new java.awt.GridBagLayout());
        jPanel2.add(jLabel1, new java.awt.GridBagConstraints());

        nombreAdmJlb.setBackground(new java.awt.Color(153, 153, 153));
        nombreAdmJlb.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nombreAdmJlb.setForeground(new java.awt.Color(51, 51, 51));
        nombreAdmJlb.setText("ADMINISTRADOR...");
        jPanel2.add(nombreAdmJlb, new java.awt.GridBagConstraints());

        jPanel12.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel12, new java.awt.GridBagConstraints());

        jPanel13.setBackground(new java.awt.Color(102, 102, 102));
        jPanel13.setPreferredSize(new java.awt.Dimension(140, 12));
        jPanel13.setLayout(new java.awt.GridBagLayout());

        txtBusca.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        txtBusca.setForeground(java.awt.Color.gray);
        txtBusca.setText("Buscar.................");
        txtBusca.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtBusca.setPreferredSize(new java.awt.Dimension(180, 22));
        txtBusca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBuscaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBuscaFocusLost(evt);
            }
        });
        txtBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 533;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(37, 25, 31, 0);
        jPanel13.add(txtBusca, gridBagConstraints);

        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(37, 18, 31, 0);
        jPanel13.add(jButton1, gridBagConstraints);

        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(37, 6, 31, 37);
        jPanel13.add(jButton2, gridBagConstraints);

        Añadirbnt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image (19).png"))); // NOI18N
        Añadirbnt.setBorderPainted(false);
        Añadirbnt.setContentAreaFilled(false);
        jPanel13.add(Añadirbnt, new java.awt.GridBagConstraints());

        eliminartbn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image (18).png"))); // NOI18N
        eliminartbn.setBorderPainted(false);
        eliminartbn.setContentAreaFilled(false);
        jPanel13.add(eliminartbn, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(jPanel13, gridBagConstraints);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel14, new java.awt.GridBagConstraints());

        jPanel7.add(jPanel1, java.awt.BorderLayout.CENTER);

        pnlBorde.setBackground(new java.awt.Color(204, 204, 204));
        pnlBorde.setPreferredSize(new java.awt.Dimension(800, 25));
        pnlBorde.setLayout(new javax.swing.BoxLayout(pnlBorde, javax.swing.BoxLayout.LINE_AXIS));

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home.png"))); // NOI18N
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        pnlBorde.add(btnHome);

        btnRecargar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recargar.png"))); // NOI18N
        btnRecargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecargarActionPerformed(evt);
            }
        });
        pnlBorde.add(btnRecargar);

        btnOpciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/opciones.png"))); // NOI18N
        pnlBorde.add(btnOpciones);

        jPanel7.add(pnlBorde, java.awt.BorderLayout.PAGE_START);

        jPanel5.add(jPanel7, java.awt.BorderLayout.PAGE_START);

        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel11.setPreferredSize(new java.awt.Dimension(153, 150));
        jPanel11.setLayout(new java.awt.GridLayout(0, 1));

        chuchepriasbtn.setBackground(new java.awt.Color(153, 153, 153));
        chuchepriasbtn.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        chuchepriasbtn.setText("FAMADESA");
        chuchepriasbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        chuchepriasbtn.setPreferredSize(new java.awt.Dimension(100, 30));
        chuchepriasbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chuchepriasbtnActionPerformed(evt);
            }
        });
        jPanel11.add(chuchepriasbtn);

        Snacksbtn.setBackground(new java.awt.Color(153, 153, 153));
        Snacksbtn.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        Snacksbtn.setText("ALCODIS");
        Snacksbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Snacksbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SnacksbtnActionPerformed(evt);
            }
        });
        jPanel11.add(Snacksbtn);

        Frutasbtn.setBackground(new java.awt.Color(153, 153, 153));
        Frutasbtn.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        Frutasbtn.setText("GONVADOR");
        Frutasbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Frutasbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FrutasbtnActionPerformed(evt);
            }
        });
        jPanel11.add(Frutasbtn);

        bebidasbtn.setBackground(new java.awt.Color(153, 153, 153));
        bebidasbtn.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        bebidasbtn.setText("ASSOLIN");
        bebidasbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        bebidasbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bebidasbtnActionPerformed(evt);
            }
        });
        jPanel11.add(bebidasbtn);

        pescadosbtn.setBackground(new java.awt.Color(153, 153, 153));
        pescadosbtn.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        pescadosbtn.setText("PESCAPRO");
        pescadosbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        pescadosbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pescadosbtnActionPerformed(evt);
            }
        });
        jPanel11.add(pescadosbtn);

        alcoholbtn.setBackground(new java.awt.Color(153, 153, 153));
        alcoholbtn.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        alcoholbtn.setText("PANIREST");
        alcoholbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        alcoholbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alcoholbtnActionPerformed(evt);
            }
        });
        jPanel11.add(alcoholbtn);

        CarnesBtn.setBackground(new java.awt.Color(153, 153, 153));
        CarnesBtn.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        CarnesBtn.setText("PLASTICSUR");
        CarnesBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        CarnesBtn.setPreferredSize(new java.awt.Dimension(150, 23));
        CarnesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarnesBtnActionPerformed(evt);
            }
        });
        jPanel11.add(CarnesBtn);

        jScrollPane1.setViewportView(jPanel11);

        jPanel6.add(jScrollPane1, java.awt.BorderLayout.LINE_START);

        pnlContenido.setPreferredSize(new java.awt.Dimension(800, 800));
        pnlContenido.setLayout(new java.awt.GridLayout(1, 0));
        jPanel6.add(pnlContenido, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel6, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1011, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscaFocusGained
        // TODO add your handling code here:
        if (txtBusca.getText().equals("Buscar............................")) {
            txtBusca.setText("");
            txtBusca.setForeground(Color.BLACK);
        }

    }//GEN-LAST:event_txtBuscaFocusGained

    private void txtBuscaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscaFocusLost
        // TODO add your handling code here:
        if (txtBusca.getText().isEmpty()) {
            txtBusca.setForeground(Color.GRAY);
            txtBusca.setText("Buscar......................");
        }

    }//GEN-LAST:event_txtBuscaFocusLost

    private void txtBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscaActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        Home home = new Home();
        home.setVisible(true);
        home.setLocationRelativeTo(null); // Centra la ventana

        // Cierra la ventana actual
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnRecargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecargarActionPerformed
        this.dispose(); // Cierra la ventana actual
        Home nuevaVentana = new Home(); // Crea una nueva instancia
        nuevaVentana.setVisible(true); // Muestra la nueva
        nuevaVentana.setLocationRelativeTo(null); // La centra en pantalla
    }//GEN-LAST:event_btnRecargarActionPerformed

    private void chuchepriasbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chuchepriasbtnActionPerformed
        // TODO add your handling code here:ç
        cambiarPanel(new pnlProveedor());
    }//GEN-LAST:event_chuchepriasbtnActionPerformed

    private void SnacksbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SnacksbtnActionPerformed
        // TODO add your handling code here:
        cambiarPanel(new pnlProveedor());
    }//GEN-LAST:event_SnacksbtnActionPerformed

    private void FrutasbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FrutasbtnActionPerformed
        // TODO add your handling code here:
        cambiarPanel(new pnlProveedor());
    }//GEN-LAST:event_FrutasbtnActionPerformed

    private void bebidasbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bebidasbtnActionPerformed
        // TODO add your handling code here:
        cambiarPanel(new pnlProveedor());

    }//GEN-LAST:event_bebidasbtnActionPerformed

    private void pescadosbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pescadosbtnActionPerformed
        // TODO add your handling code here:
        cambiarPanel(new pnlProveedor());
    }//GEN-LAST:event_pescadosbtnActionPerformed

    private void alcoholbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alcoholbtnActionPerformed
        // TODO add your handling code here:
        cambiarPanel(new pnlProveedor());
    }//GEN-LAST:event_alcoholbtnActionPerformed

    private void CarnesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarnesBtnActionPerformed
        // TODO add your handling code here:
        cambiarPanel(new pnlProveedor());
    }//GEN-LAST:event_CarnesBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new proveedores().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Añadirbnt;
    private javax.swing.JButton CarnesBtn;
    private javax.swing.JButton Frutasbtn;
    private javax.swing.JButton Snacksbtn;
    private javax.swing.JButton alcoholbtn;
    private javax.swing.JButton bebidasbtn;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnOpciones;
    private javax.swing.JButton btnRecargar;
    private javax.swing.JButton chuchepriasbtn;
    private javax.swing.JButton eliminartbn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nombreAdmJlb;
    private javax.swing.JButton pescadosbtn;
    private javax.swing.JPanel pnlBorde;
    private javax.swing.JPanel pnlContenido;
    private javax.swing.JTextField txtBusca;
    // End of variables declaration//GEN-END:variables
}
