/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.supermercadoproyecto.administrador;

import com.mycompany.supermercadoproyecto.login.Home;
import com.mycompany.supermercadoproyecto.administrador.HerramientasAdministrador;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.Insets;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JSeparator;
import javax.swing.JTextField;
import javax.swing.UIManager;

/**
 *
 * @author MEDAC
 */
public class Gestión_empleados extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Gestión_empleados.class.getName());

    /**
     * Creates new form Home
     */
    public Gestión_empleados() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
       // Aseguramos layout de pnlHome
GridBagLayout layout = (GridBagLayout) pnlHome.getLayout();
pnlHome.remove(btnAlta);
pnlHome.remove(btnModificar);
pnlHome.remove(btnBaja);

// Creamos un subpanel para agrupar los botones
JPanel pnlBotones = new JPanel(new FlowLayout(FlowLayout.CENTER, 75, 0));
pnlBotones.setOpaque(false); // Fondo transparente
pnlBotones.add(btnAlta);
pnlBotones.add(btnModificar);
pnlBotones.add(btnBaja);

// Configuramos constraints para centrar el bloque
GridBagConstraints gbc = new GridBagConstraints();
gbc.gridx = 0;
gbc.gridy = 1;
gbc.gridwidth = 3;
gbc.anchor = GridBagConstraints.CENTER;
gbc.fill = GridBagConstraints.NONE;
gbc.weightx = 1.0;
gbc.weighty = 1.0;

// Añadimos el subpanel al pnlHome
pnlHome.add(pnlBotones, gbc);

// Forzamos actualización visual
pnlHome.revalidate();
pnlHome.repaint();
// Centrar el jLabel1 arriba
GridBagConstraints gbcTitulo = new GridBagConstraints();
gbcTitulo.gridx = 0;
gbcTitulo.gridy = 0;
gbcTitulo.gridwidth = 3; // mismo número de columnas que uses para los botones
gbcTitulo.anchor = GridBagConstraints.PAGE_START;
gbcTitulo.fill = GridBagConstraints.NONE;
gbcTitulo.weightx = 1.0;
gbcTitulo.weighty = 0.0;
gbcTitulo.insets = new Insets(30, 0, 20, 0);

pnlHome.add(jblEmpleados, gbcTitulo);
pnlHome.revalidate();
pnlHome.repaint();

  

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlPrincipal = new javax.swing.JPanel();
        pnlBorde = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnRecargar = new javax.swing.JButton();
        btnOpciones = new javax.swing.JButton();
        pnlHome = new com.mycompany.supermercadoproyecto.recursos.BackgroundPanel("/fondo.png");
        pnlHome = new com.mycompany.supermercadoproyecto.recursos.BackgroundPanel("/fondo.png")
        ;
        jblEmpleados = new javax.swing.JLabel();
        btnAlta = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnBaja = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPrincipal.setLayout(new java.awt.BorderLayout());

        pnlBorde.setBackground(new java.awt.Color(204, 204, 204));
        pnlBorde.setPreferredSize(new java.awt.Dimension(800, 25));
        pnlBorde.setLayout(new javax.swing.BoxLayout(pnlBorde, javax.swing.BoxLayout.LINE_AXIS));

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home.png"))); // NOI18N
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        pnlBorde.add(btnHome);

        btnRecargar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recargar.png"))); // NOI18N
        btnRecargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecargarActionPerformed(evt);
            }
        });
        pnlBorde.add(btnRecargar);

        btnOpciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/opciones.png"))); // NOI18N
        btnOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcionesActionPerformed(evt);
            }
        });
        pnlBorde.add(btnOpciones);

        pnlPrincipal.add(pnlBorde, java.awt.BorderLayout.PAGE_START);

        pnlHome.setLayout(new java.awt.GridBagLayout());

        jblEmpleados.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 48)); // NOI18N
        jblEmpleados.setForeground(new java.awt.Color(255, 255, 255));
        jblEmpleados.setText("Gestión de empleados");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        pnlHome.add(jblEmpleados, gridBagConstraints);

        btnAlta.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btnAlta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alta.png"))); // NOI18N
        btnAlta.setText("Alta");
        btnAlta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 19;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 28, 10, 28);
        pnlHome.add(btnAlta, gridBagConstraints);

        btnModificar.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modificación.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 19;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 28, 10, 28);
        pnlHome.add(btnModificar, gridBagConstraints);

        btnBaja.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btnBaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baja.png"))); // NOI18N
        btnBaja.setText("Baja");
        btnBaja.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 19;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 28, 10, 28);
        pnlHome.add(btnBaja, gridBagConstraints);

        pnlPrincipal.add(pnlHome, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
    Home home = new Home();
    home.setVisible(true);
    home.setLocationRelativeTo(null); // Centra la ventana

    // Cierra la ventana actual
    this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaActionPerformed
        // --- 1. CONFIGURACIÓN VISUAL ---
        Color fondo = new Color(255, 255, 255);
        Color grisTexto = new Color(100, 100, 100);
        Font fuenteTitulo = new Font("Segoe UI", Font.BOLD, 18);
        Font fuenteLabel = new Font("Segoe UI", Font.PLAIN, 13);

// --- 2. CREACIÓN DE COMPONENTES ---
        JTextField txtNombre = new JTextField();
        JTextField txtApellido = new JTextField();
        JTextField txtDni = new JTextField();
        JTextField txtUsuario = new JTextField();
        JPasswordField txtPass = new JPasswordField();
// El ComboBox toma los valores de tu Enum Rol
        JComboBox<com.supermercado.modelos.Rol> cmbRol = new JComboBox<>(com.supermercado.modelos.Rol.values());

// Decoración
        Dimension campoSize = new Dimension(220, 30);
        JComponent[] campos = {txtNombre, txtApellido, txtDni, txtUsuario, txtPass, cmbRol};
        for (JComponent c : campos) {
            c.setPreferredSize(campoSize);
            c.setBorder(BorderFactory.createCompoundBorder(
                    BorderFactory.createLineBorder(new Color(200, 200, 200)),
                    BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        }

// Truco: Copiar DNI a Usuario automáticamente al escribir
        txtDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUsuario.setText(txtDni.getText());
            }
        });

// --- 3. ARMANDO EL PANEL ---
        JPanel panel = new JPanel(new GridBagLayout());
        panel.setBackground(fondo);
        panel.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));

        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(8, 10, 8, 10);
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.anchor = GridBagConstraints.WEST;

// Título
        JLabel lblTitulo = new JLabel("Registrar Nuevo Empleado");
        lblTitulo.setFont(fuenteTitulo);
        lblTitulo.setForeground(new Color(50, 50, 150));
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        gbc.insets = new Insets(0, 10, 20, 10);
        panel.add(lblTitulo, gbc);

// Reset para campos
        gbc.gridwidth = 1;
        gbc.insets = new Insets(5, 10, 5, 10);

// Añadimos los campos (YA NO ESTÁ EL CHECKBOX)
        agregarCampo(panel, gbc, 1, "Nombre:", txtNombre, fuenteLabel);
        agregarCampo(panel, gbc, 2, "Apellido:", txtApellido, fuenteLabel);
        agregarCampo(panel, gbc, 3, "DNI:", txtDni, fuenteLabel);
        agregarCampo(panel, gbc, 4, "Usuario:", txtUsuario, fuenteLabel);
        agregarCampo(panel, gbc, 5, "Contraseña:", txtPass, fuenteLabel);
        agregarCampo(panel, gbc, 6, "Rol:", cmbRol, fuenteLabel);

// --- 4. MOSTRAR DIÁLOGO ---
        int option = JOptionPane.showConfirmDialog(this, panel, "Nuevo Empleado",
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

// --- 5. LÓGICA DE GUARDADO ---
        if (option == JOptionPane.OK_OPTION) {
            // A. Capturar datos
            String nombre = txtNombre.getText().trim();
            String apellido = txtApellido.getText().trim();
            String dni = txtDni.getText().trim();
            String usuario = txtUsuario.getText().trim();
            String password = new String(txtPass.getPassword());
            com.supermercado.modelos.Rol rol = (com.supermercado.modelos.Rol) cmbRol.getSelectedItem();

            // B. Validación
            if (nombre.isEmpty() || usuario.isEmpty() || password.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Nombre, Usuario y Contraseña son obligatorios.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            try {
                // C. Crear Objeto
                com.supermercado.modelos.Empleado emp = new com.supermercado.modelos.Empleado();
                emp.setNombre(nombre);
                emp.setApellido(apellido);
                emp.setDni(dni);
                emp.setUsuario(usuario);
                emp.setPassword(password);
                emp.setRol(rol);

                // IMPORTANTE: Lo activamos por defecto internamente
                // Si no hacemos esto, no podrá iniciar sesión
                emp.setActivo(true);

                // ... dentro del try ...
// D. Guardar
                com.supermercado.dao.EmpleadoDAO dao = new com.supermercado.dao.EmpleadoDAO();
                dao.registrar(emp);

// =================================================================
// TRAZABILIDAD
// =================================================================
                try {
                    com.supermercado.modelos.Empleado admin = com.supermercado.util.Sesion.getEmpleado();
                    String accion = "Registró al nuevo empleado: " + emp.getDni();
                    new com.supermercado.dao.LogDAO().registrarLog(admin, accion);
                } catch (Exception e) {
                    System.out.println("Error al guardar log: " + e.getMessage());
                }
// =================================================================

                JOptionPane.showMessageDialog(this, "¡Empleado creado correctamente!", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Error al guardar: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnAltaActionPerformed

    private void agregarCampo(JPanel p, GridBagConstraints g, int fila, String texto, JComponent campo, Font f) {
    g.gridy = fila;
    g.gridx = 0;
    JLabel label = new JLabel(texto);
    label.setFont(f);
    p.add(label, g);
    
    g.gridx = 1;
    p.add(campo, g);
}
    
    private void btnRecargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecargarActionPerformed
    this.dispose(); // Cierra la ventana actual
    Gestión_empleados nuevaVentana = new Gestión_empleados(); // Crea una nueva instancia
    nuevaVentana.setVisible(true); // Muestra la nueva
    nuevaVentana.setLocationRelativeTo(null); // La centra en pantalla
    }//GEN-LAST:event_btnRecargarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // 1. --- PREPARAR DATOS (DAO) ---
        com.supermercado.dao.EmpleadoDAO dao = new com.supermercado.dao.EmpleadoDAO();
        java.util.List<com.supermercado.modelos.Empleado> listaEmpleados = dao.listarTodos();

// Si no hay empleados, avisamos y salimos
        if (listaEmpleados.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay empleados registrados para modificar.");
            return;
        }

// 2. --- COMPONENTES VISUALES ---
// El desplegable (JComboBox) con los objetos Empleado directos
        JComboBox<com.supermercado.modelos.Empleado> cmbEmpleados = new JComboBox<>();
        for (com.supermercado.modelos.Empleado e : listaEmpleados) {
            cmbEmpleados.addItem(e);
        }

// Campos para editar
        JTextField txtDni = new JTextField();
        JTextField txtUsuario = new JTextField(); // Este será de solo lectura para ver el efecto
        JTextField txtNombre = new JTextField();
        JTextField txtApellido = new JTextField();
        JPasswordField txtPass = new JPasswordField();

// Configuración estética
        txtUsuario.setEditable(false); // El usuario se cambia solo, no se toca a mano
        txtUsuario.setBackground(new Color(230, 230, 230)); // Gris para indicar que es automático

        Dimension campoSize = new Dimension(220, 30);
        JComponent[] campos = {cmbEmpleados, txtDni, txtUsuario, txtNombre, txtApellido, txtPass};
        for (JComponent c : campos) {
            c.setPreferredSize(campoSize);
        }

// 3. --- EVENTOS MÁGICOS (LISTENERS) ---
// A. Cuando seleccionas a alguien en el desplegable -> Rellenar campos
        cmbEmpleados.addActionListener(e -> {
            com.supermercado.modelos.Empleado seleccionado = (com.supermercado.modelos.Empleado) cmbEmpleados.getSelectedItem();
            if (seleccionado != null) {
                txtDni.setText(seleccionado.getDni());
                txtUsuario.setText(seleccionado.getUsuario());
                txtNombre.setText(seleccionado.getNombre());
                txtApellido.setText(seleccionado.getApellido());
                txtPass.setText(""); // La contraseña se deja vacía por seguridad (solo llenar si se quiere cambiar)
            }
        });

// B. Cuando escribes en el DNI -> Se copia al Usuario en tiempo real
        txtDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUsuario.setText(txtDni.getText());
            }
        });

// Forzamos la selección del primero para llenar los campos al abrir la ventana
        if (cmbEmpleados.getItemCount() > 0) {
            cmbEmpleados.setSelectedIndex(0);
        }

// 4. --- PANEL VISUAL (DISEÑO) ---
        JPanel panel = new JPanel(new GridBagLayout());
        panel.setBackground(Color.WHITE);
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(5, 5, 5, 5);
        gbc.anchor = GridBagConstraints.WEST;

// Usamos tu método auxiliar 'agregarCampo'
        agregarCampo(panel, gbc, 0, "Seleccionar Empleado:", cmbEmpleados, new Font("Segoe UI", Font.BOLD, 13));

// Separador visual
        gbc.gridy = 1;
        panel.add(new JSeparator(), gbc);

        agregarCampo(panel, gbc, 2, "DNI (Editable):", txtDni, new Font("Segoe UI", Font.PLAIN, 13));
        agregarCampo(panel, gbc, 3, "Usuario (Automático):", txtUsuario, new Font("Segoe UI", Font.PLAIN, 13));
        agregarCampo(panel, gbc, 4, "Nombre:", txtNombre, new Font("Segoe UI", Font.PLAIN, 13));
        agregarCampo(panel, gbc, 5, "Apellido:", txtApellido, new Font("Segoe UI", Font.PLAIN, 13));
        agregarCampo(panel, gbc, 6, "Nueva Contraseña:", txtPass, new Font("Segoe UI", Font.PLAIN, 13));

// 5. --- MOSTRAR Y GUARDAR ---
        int option = JOptionPane.showConfirmDialog(this, panel, "Modificar Empleado", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

        if (option == JOptionPane.OK_OPTION) {
            try {
                // 1. OBTENER EL ORIGINAL (El "Antes")
                com.supermercado.modelos.Empleado original = (com.supermercado.modelos.Empleado) cmbEmpleados.getSelectedItem();
                String dniOriginal = original.getDni();

                // 2. OBTENER LOS NUEVOS DATOS (El "Después")
                String nuevoDni = txtDni.getText().trim();
                String nuevoNombre = txtNombre.getText().trim();
                String nuevoApellido = txtApellido.getText().trim();
                String nuevaPass = new String(txtPass.getPassword());

                if (nuevoDni.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "El DNI no puede estar vacío.");
                    return;
                }

                // =====================================================================
                // 3. EL DETECTIVE: Comparar qué ha cambiado
                // Usamos StringBuilder que es como una "bolsa" para ir metiendo textos
                // =====================================================================
                StringBuilder cambiosDetectados = new StringBuilder();

                // A. Comprobar DNI
                if (!original.getDni().equals(nuevoDni)) {
                    cambiosDetectados.append("[DNI: '").append(original.getDni()).append("' -> '").append(nuevoDni).append("'] ");
                }

                // B. Comprobar Nombre
                if (!original.getNombre().equals(nuevoNombre)) {
                    cambiosDetectados.append("[Nombre: '").append(original.getNombre()).append("' -> '").append(nuevoNombre).append("'] ");
                }

                // C. Comprobar Apellido
                // (Usamos un truco por si el apellido original era null para evitar errores)
                String apellidoViejo = (original.getApellido() == null) ? "" : original.getApellido();
                if (!apellidoViejo.equals(nuevoApellido)) {
                    cambiosDetectados.append("[Apellido: '").append(apellidoViejo).append("' -> '").append(nuevoApellido).append("'] ");
                }

                // D. Comprobar Contraseña (Solo indicamos que cambió, no mostramos la clave por seguridad)
                if (!nuevaPass.isEmpty()) {
                    cambiosDetectados.append("[Contraseña cambiada] ");
                }

                // Si no hubo cambios, no molestamos a la base de datos
                if (cambiosDetectados.length() == 0) {
                    JOptionPane.showMessageDialog(this, "No realizaste ningún cambio en los datos.");
                    return;
                }
                // =====================================================================

                // 4. LLAMAR AL DAO PARA GUARDAR
                boolean exito = dao.modificar(dniOriginal, nuevoDni, nuevoNombre, nuevoApellido, nuevaPass);

                if (exito) {
                    // =================================================================
                    // 5. GUARDAR EN EL LOG CON DETALLES
                    // =================================================================
                    try {
                        com.supermercado.modelos.Empleado admin = com.supermercado.util.Sesion.getEmpleado();

                        // El mensaje final será tipo: "Modificó a 1234A: [Nombre: 'Juan' -> 'Pedro'] [Apellido...]"
                        String accion = "Modificó a " + dniOriginal + ": " + cambiosDetectados.toString();

                        new com.supermercado.dao.LogDAO().registrarLog(admin, accion);

                    } catch (Exception e) {
                        System.out.println("Error log: " + e.getMessage());
                    }
                    // =================================================================

                    JOptionPane.showMessageDialog(this, "¡Empleado actualizado correctamente!", "Éxito", JOptionPane.INFORMATION_MESSAGE);

                    // Opcional: Recargar el desplegable por si cambiaste el nombre y quieres verlo actualizado al instante
                    // (Si tienes el código del desplegable en una función aparte, llámala aquí)
                } else {
                    JOptionPane.showMessageDialog(this, "Error al actualizar.", "Error", JOptionPane.ERROR_MESSAGE);
                }

            } catch (Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Error crítico: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaActionPerformed
        // 1. --- PREPARAR DATOS ---
        com.supermercado.dao.EmpleadoDAO dao = new com.supermercado.dao.EmpleadoDAO();
        java.util.List<com.supermercado.modelos.Empleado> listaEmpleados = dao.listarTodos();

        if (listaEmpleados.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay empleados registrados para eliminar.");
            return;
        }

// 2. --- CONFIGURACIÓN VISUAL ---
        Color fondo = new Color(255, 255, 255);
        Font fuenteTitulo = new Font("Segoe UI", Font.BOLD, 14);

// 3. --- CREAR DESPLEGABLE ---
        JComboBox<com.supermercado.modelos.Empleado> cmbEmpleados = new JComboBox<>();
        for (com.supermercado.modelos.Empleado e : listaEmpleados) {
            cmbEmpleados.addItem(e); // Gracias al toString() se verán los nombres bonitos
        }
        cmbEmpleados.setPreferredSize(new Dimension(250, 30));

// 4. --- PANEL DE DISEÑO ---
        JPanel panel = new JPanel(new GridBagLayout());
        panel.setBackground(fondo);
        panel.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));

        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(10, 10, 10, 10);
        gbc.gridx = 0;
        gbc.gridy = 0;

// Icono de advertencia (opcional, usa uno del sistema si no tienes imagen)
        JLabel lblIcono = new JLabel(UIManager.getIcon("OptionPane.warningIcon"));
        panel.add(lblIcono, gbc);

// Texto y Desplegable
        gbc.gridx = 1;
        gbc.anchor = GridBagConstraints.WEST;
        JLabel lblTexto = new JLabel("Seleccione el empleado a eliminar:");
        lblTexto.setFont(fuenteTitulo);
        panel.add(lblTexto, gbc);

        gbc.gridy = 1;
        panel.add(cmbEmpleados, gbc);

// Mensaje de aviso en rojo
        gbc.gridy = 2;
        JLabel lblAviso = new JLabel("<html><font color='red'>¡Atención! Esta acción no se puede deshacer.</font></html>");
        panel.add(lblAviso, gbc);

// 5. --- MOSTRAR DIÁLOGO ---
        int option = JOptionPane.showConfirmDialog(this, panel, "Eliminar Empleado",
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);

// 6. --- LÓGICA DE BORRADO ---
        if (option == JOptionPane.OK_OPTION) {
            try {
                // Obtenemos el empleado seleccionado
                com.supermercado.modelos.Empleado seleccionado = (com.supermercado.modelos.Empleado) cmbEmpleados.getSelectedItem();

                // Confirmación extra de seguridad
                int confirm = JOptionPane.showConfirmDialog(this,
                        "¿Seguro que deseas eliminar a " + seleccionado.getNombre() + "?",
                        "Confirmar eliminación",
                        JOptionPane.YES_NO_OPTION);

                if (confirm == JOptionPane.YES_OPTION) {
                    boolean eliminado = dao.eliminar(seleccionado.getDni());

                    if (eliminado) {
                        // =================================================================
                        // TRAZABILIDAD
                        // =================================================================
                        try {
                            com.supermercado.modelos.Empleado admin = com.supermercado.util.Sesion.getEmpleado();
                            String accion = "Eliminó al empleado: " + seleccionado.getDni() + " (" + seleccionado.getNombre() + ")";
                            new com.supermercado.dao.LogDAO().registrarLog(admin, accion);
                        } catch (Exception e) {
                            System.out.println("Error al guardar log: " + e.getMessage());
                        }
                        // =================================================================

                        JOptionPane.showMessageDialog(this, "Empleado eliminado correctamente.");
                    } else {
                        // ... mensaje de error ...
                    }
                }
            } catch (Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Error crítico: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnBajaActionPerformed

    private void btnOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcionesActionPerformed
    HerramientasAdministrador herramientas = new HerramientasAdministrador();
    this.dispose();
    herramientas.setVisible(true);
    herramientas.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnOpcionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Gestión_empleados().setVisible(true));
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlta;
    private javax.swing.JButton btnBaja;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnOpciones;
    private javax.swing.JButton btnRecargar;
    private javax.swing.JLabel jblEmpleados;
    private javax.swing.JPanel pnlBorde;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}

