/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.supermercadoproyecto.administrador;

import com.supermercado.dao.LogDAO;
import com.supermercado.modelos.Log;
import com.supermercado.util.Sesion;
import javax.swing.DefaultListModel;
import java.time.format.DateTimeFormatter;
import com.mycompany.supermercadoproyecto.login.Home;
import com.mycompany.supermercadoproyecto.administrador.HerramientasAdministrador;

/**
 *
 * @author MEDAC
 */
public class Informes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Informes.class.getName());

    /**
     * Creates new form Informes
     */
    public Informes() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);

        // --- AÑADE ESTO ---
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        contenedorPrincipal = new javax.swing.JPanel();
        contenedorArriba = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        nombreAdmJlb = new javax.swing.JLabel();
        dniAdministradorJlb = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnlBorde = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnRecargar = new javax.swing.JButton();
        btnOpciones = new javax.swing.JButton();
        contenedorAbajo = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        listaPromocionesReportes = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        listaStockReportes = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaEmpleadosReportes = new javax.swing.JList<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        listaproductosReportes = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        contenedorPrincipal.setLayout(new java.awt.BorderLayout());

        contenedorArriba.setLayout(new java.awt.BorderLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(200, 200));
        jPanel1.setPreferredSize(new java.awt.Dimension(440, 100));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel12.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setPreferredSize(new java.awt.Dimension(155, 100));
        jPanel2.setLayout(new java.awt.GridLayout(0, 1));

        nombreAdmJlb.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nombreAdmJlb.setForeground(new java.awt.Color(51, 51, 51));
        nombreAdmJlb.setText("ADMINISTRADOR...");
        jPanel2.add(nombreAdmJlb);

        dniAdministradorJlb.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dniAdministradorJlb.setForeground(new java.awt.Color(51, 51, 51));
        dniAdministradorJlb.setText("NIF/DNI...");
        jPanel2.add(dniAdministradorJlb);

        jPanel12.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel12, new java.awt.GridBagConstraints());

        jPanel13.setBackground(new java.awt.Color(102, 102, 102));
        jPanel13.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("INFORMES Y FACTURACIÓN");
        jPanel13.add(jLabel1, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(jPanel13, gridBagConstraints);

        jPanel14.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/massi-cuadrado-100.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel4.add(jLabel2, gridBagConstraints);

        jPanel14.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel14, new java.awt.GridBagConstraints());

        contenedorArriba.add(jPanel1, java.awt.BorderLayout.CENTER);

        pnlBorde.setBackground(new java.awt.Color(204, 204, 204));
        pnlBorde.setPreferredSize(new java.awt.Dimension(800, 25));
        pnlBorde.setLayout(new javax.swing.BoxLayout(pnlBorde, javax.swing.BoxLayout.LINE_AXIS));

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home.png"))); // NOI18N
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        pnlBorde.add(btnHome);

        btnRecargar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recargar.png"))); // NOI18N
        btnRecargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecargarActionPerformed(evt);
            }
        });
        pnlBorde.add(btnRecargar);

        btnOpciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/opciones.png"))); // NOI18N
        btnOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcionesActionPerformed(evt);
            }
        });
        pnlBorde.add(btnOpciones);

        contenedorArriba.add(pnlBorde, java.awt.BorderLayout.PAGE_START);

        contenedorPrincipal.add(contenedorArriba, java.awt.BorderLayout.PAGE_START);

        contenedorAbajo.setLayout(new java.awt.BorderLayout());

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));
        jPanel8.setLayout(new java.awt.GridLayout(1, 0));

        jPanel9.setLayout(new java.awt.GridBagLayout());

        jLabel8.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        jLabel8.setText("<html>{nombre}<br><br>Infomación<br> del admin <br><br><br> NIF:<br> {nif} <br> <br><br>Teléfono: <br>{telefono} </html>");
        jLabel8.setPreferredSize(new java.awt.Dimension(100, 400));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weighty = 1.0;
        jPanel9.add(jLabel8, gridBagConstraints);

        jPanel8.add(jPanel9);

        contenedorAbajo.add(jPanel8, java.awt.BorderLayout.LINE_END);

        jPanel10.setBackground(new java.awt.Color(153, 153, 153));
        jPanel10.setLayout(new java.awt.GridLayout(2, 2));

        listaPromocionesReportes.setBackground(new java.awt.Color(153, 153, 153));
        listaPromocionesReportes.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 1, 1, 1, new java.awt.Color(51, 51, 51)));
        listaPromocionesReportes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "<html><p><b><font color=\"red\" size=\"5\">MODIFICACIÓN</font></b></html>", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(listaPromocionesReportes);

        jPanel10.add(jScrollPane5);

        listaStockReportes.setBackground(new java.awt.Color(153, 153, 153));
        listaStockReportes.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 1, 1, 1, new java.awt.Color(51, 51, 51)));
        listaStockReportes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "<html><p><b><font color=\"red\" size=\"5\">CAJA</font></b></html>", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane6.setViewportView(listaStockReportes);

        jPanel10.add(jScrollPane6);

        listaEmpleadosReportes.setBackground(new java.awt.Color(153, 153, 153));
        listaEmpleadosReportes.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 1, 1, 1, new java.awt.Color(51, 51, 51)));
        listaEmpleadosReportes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "<html><p><b><font color=\"red\" size=\"5\">PEDIDOS</font></b></html>", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(listaEmpleadosReportes);

        jPanel10.add(jScrollPane3);

        listaproductosReportes.setBackground(new java.awt.Color(153, 153, 153));
        listaproductosReportes.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 1, 1, 1, new java.awt.Color(51, 51, 51)));
        listaproductosReportes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "<html><p><b><font color=\"red\" size=\"5\">REGISTRO DIARIO</font></b></html>", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane7.setViewportView(listaproductosReportes);

        jPanel10.add(jScrollPane7);

        contenedorAbajo.add(jPanel10, java.awt.BorderLayout.CENTER);

        contenedorPrincipal.add(contenedorAbajo, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedorPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedorPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        Home home = new Home();
        home.setVisible(true);
        home.setLocationRelativeTo(null); // Centra la ventana

        // Cierra la ventana actual
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnRecargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecargarActionPerformed
        this.dispose(); // Cierra la ventana actual
        Informes nuevaVentana = new Informes(); // Crea una nueva instancia
        nuevaVentana.setVisible(true); // Muestra la nueva
        nuevaVentana.setLocationRelativeTo(null); // La centra en pantalla
    }//GEN-LAST:event_btnRecargarActionPerformed

    private void btnOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcionesActionPerformed
        HerramientasAdministrador herramientas = new HerramientasAdministrador();
    this.dispose();
    herramientas.setVisible(true);
    herramientas.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnOpcionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Informes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnOpciones;
    private javax.swing.JButton btnRecargar;
    private javax.swing.JPanel contenedorAbajo;
    private javax.swing.JPanel contenedorArriba;
    private javax.swing.JPanel contenedorPrincipal;
    private javax.swing.JLabel dniAdministradorJlb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JList<String> listaEmpleadosReportes;
    private javax.swing.JList<String> listaPromocionesReportes;
    private javax.swing.JList<String> listaStockReportes;
    private javax.swing.JList<String> listaproductosReportes;
    private javax.swing.JLabel nombreAdmJlb;
    private javax.swing.JPanel pnlBorde;
    // End of variables declaration//GEN-END:variables
// --- MÉTODO PARA CARGAR DATOS DE LA BASE DE DATOS ---
    private void cargarDatos() {
        // A. Cargar datos del Administrador actual (Panel Izquierdo Arriba)
        if (Sesion.getEmpleado() != null) {
            nombreAdmJlb.setText(Sesion.getEmpleado().getNombre().toUpperCase());
            dniAdministradorJlb.setText(Sesion.getEmpleado().getDni());

            // Actualizar el panel lateral derecho con info detallada
            String infoHtml = "<html>" + Sesion.getEmpleado().getNombre() + "<br><br>"
                    + "Información<br> del admin <br><br><br>"
                    + "NIF:<br> " + Sesion.getEmpleado().getDni() + " <br> <br><br>"
                    + "Teléfono: <br>" + "No disponible" + " </html>"; // Si añades teléfono a Empleado, ponlo aquí
            jLabel8.setText(infoHtml);
        }

        // B. Preparar herramientas para leer Logs
        LogDAO dao = new LogDAO();
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("HH:mm dd/MM");

        // --- 1. LLENAR LISTA DE MODIFICACIONES ---
        // (Tu variable se llama listaPromocionesReportes según el código que pasaste)
        DefaultListModel<String> modeloMod = new DefaultListModel<>();

        // Mantenemos el título rojo HTML que tenías
        modeloMod.addElement("<html><p><b><font color=\"red\" size=\"5\">MODIFICACIÓN</font></b></html>");

        java.util.List<Log> logsMod = dao.obtenerLogsModificaciones();

        if (logsMod.isEmpty()) {
            modeloMod.addElement("Sin modificaciones recientes.");
        } else {
            for (Log log : logsMod) {
                // Formato: "Juan: Modificó precio... (10:30 12/05)"
                String autor = (log.getEmpleado() != null) ? log.getEmpleado().getNombre() : "Sistema";
                String linea = "<html><b>" + autor + ":</b> " + log.getAccion()
                        + " <font color='gray'>(" + log.getFecha().format(formato) + ")</font></html>";
                modeloMod.addElement(linea);
            }
        }
        listaPromocionesReportes.setModel(modeloMod);

        // --- 2. LLENAR LISTA DE REGISTRO DIARIO ---
        // (Tu variable se llama listaproductosReportes según el código que pasaste)
        DefaultListModel<String> modeloDiario = new DefaultListModel<>();

        // Mantenemos el título rojo HTML
        modeloDiario.addElement("<html><p><b><font color=\"red\" size=\"5\">REGISTRO DIARIO</font></b></html>");

        java.util.List<Log> logsLogin = dao.obtenerLogsLogin();

        if (logsLogin.isEmpty()) {
            modeloDiario.addElement("Sin registros de hoy.");
        } else {
            for (Log log : logsLogin) {
                if (log.getEmpleado() != null) {
                    // Formato solicitado: "Mario con dni... inicio sesión a las..."
                    String fechaStr = log.getFecha().format(formato);
                    String texto = "<html>" + log.getEmpleado().getNombre()
                            + " (DNI " + log.getEmpleado().getDni() + ")<br>"
                            + " inició sesión a las " + fechaStr + "</html>";
                    modeloDiario.addElement(texto);
                }
            }
        }
        listaproductosReportes.setModel(modeloDiario);
    }
}
